HW3: Init
slkrylov/otus-golang-hw pull request #3
Opened 2024-02-22 12:58 UTC by slkrylov

2024-02-22 13:59 UTC, vladislavmass requested changes

2024-02-22 13:59 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return words[:top10]
Если в words будет менее 10 слов то будет паника

2024-02-27 14:53 UTC, vladislavmass approved these changes

2024-02-27 14:53 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return words[:topX]
Спорный вариант. Таким образом мы вернем полный массив word, у которого просто len будет равне topX и получится что если в массиве words 40 000 слов, то мы ради 10 из них таскаем за собой все 40к

2024-02-28 07:56 UTC, slkrylov commented on hw03_frequency_analysis/top.go
> +	return words[:topX]
Спасибо за замечание. Я согласен, что это спорное решение,  я когда писал не подумал про то, что весь  массив будет существовать до тех пор пока существует указатель на него.  Какой вариант вы бы использовали? копирование topX в отдельный массив и возврат нового массива?

2024-02-28 10:47 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return words[:topX]
Да, копирование в новый массив тут будет оптимальным вариантом

2024-02-29 07:34 UTC, merged