Hw04 lru cache
slkrylov/otus-golang-hw pull request #4
Opened 2024-03-18 19:00 UTC by slkrylov

2024-03-19 05:10 UTC, vladislavmass requested changes

2024-03-19 05:10 UTC, vladislavmass commented on hw04_lru_cache/lru.go
> +		delete(c.HashTable, key)
А разве key не является ключом нового элмента, а не последнего?

2024-03-19 05:10 UTC, vladislavmass commented on hw04_lru_cache/lru.go
> +	if c.Queue.Count > c.Capacity {
Данная реализация хоть не на долго, но создает ситуация когда размер очереди больше капасити, этого быть не должно. Правильная тактика в данном случае, вначале удаляем потом добавляем

2024-03-26 20:09 UTC, slkrylov commented on hw04_lru_cache/lru.go
> +		delete(c.HashTable, key)
Да. Вы правы. Пришлось переработать добавить дополнительную структуру чтобы можно было удалять ключу.
```
type lruValue struct {
	LruKey Key
	LruVal interface{}
}
```

2024-03-26 20:09 UTC, slkrylov commented on hw04_lru_cache/lru.go
> +	if c.Queue.Count > c.Capacity {
Спасибо за замечение. Исправил.

2024-03-27 06:07 UTC, vladislavmass approved these changes

2024-03-29 06:48 UTC, slkrylov commented
HW04: Done

2024-03-29 06:48 UTC, merged